[package]
cairo-version = "=2.10.1"
name = "death_mountain"
version = "0.1.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.1" }
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v1.0.0" }
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v1.0.0" }
tournaments = { git = "https://github.com/Provable-Games/tournaments.git" }
alexandria_encoding = { git = "https://github.com/keep-starknet-strange/alexandria.git", tag = "v0.3.0" }
graffiti = { git = "https://github.com/rsodre/graffiti", rev = "url" }

[dev-dependencies]
cairo_test = "=2.10.1"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.1" }

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = [
    "dojo::world::world_contract::world",
    "tournaments::components::models::game::m_GameMetadata",
    "tournaments::components::models::game::m_TokenMetadata",
    "tournaments::components::models::game::m_GameCounter",
    "tournaments::components::models::game::m_Score",
    "tournaments::components::models::game::m_Settings",
    "tournaments::components::models::game::m_SettingsDetails",
    "tournaments::components::models::game::m_SettingsCounter",
]

[tool.fmt]
sort-module-level-items = true
max-line-length = 120

[profile.sepolia]
[profile.slot]
[profile.mainnet]
